//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.2.2-SNAPSHOT
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:\work\SurroundWeb\private\AROS\GestureRecognizerKinectV2\\Z3Experiments\Z3Experiments\Parser\PreposeGestures.g4 by ANTLR 4.2.2-SNAPSHOT

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace PreposeGestures {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="PreposeGesturesParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.2.2-SNAPSHOT")]
[System.CLSCompliant(false)]
public interface IPreposeGesturesVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.thumbs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThumbs([NotNull] PreposeGesturesParser.ThumbsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.put_restriction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPut_restriction([NotNull] PreposeGesturesParser.Put_restrictionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.align_restriction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlign_restriction([NotNull] PreposeGesturesParser.Align_restrictionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.direction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDirection([NotNull] PreposeGesturesParser.DirectionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.hold_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHold_constraint([NotNull] PreposeGesturesParser.Hold_constraintContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.wrists"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWrists([NotNull] PreposeGesturesParser.WristsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.repeat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRepeat([NotNull] PreposeGesturesParser.RepeatContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.execution"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExecution([NotNull] PreposeGesturesParser.ExecutionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.body_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_part([NotNull] PreposeGesturesParser.Body_partContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.transform"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransform([NotNull] PreposeGesturesParser.TransformContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.pose"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPose([NotNull] PreposeGesturesParser.PoseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.center_joint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCenter_joint([NotNull] PreposeGesturesParser.Center_jointContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.side"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSide([NotNull] PreposeGesturesParser.SideContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.rotate_plane_transform"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRotate_plane_transform([NotNull] PreposeGesturesParser.Rotate_plane_transformContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.hands"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHands([NotNull] PreposeGesturesParser.HandsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.motion_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMotion_constraint([NotNull] PreposeGesturesParser.Motion_constraintContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.elbows"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElbows([NotNull] PreposeGesturesParser.ElbowsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.knees"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKnees([NotNull] PreposeGesturesParser.KneesContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.arms"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArms([NotNull] PreposeGesturesParser.ArmsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.arm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArm([NotNull] PreposeGesturesParser.ArmContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.hands_tips"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHands_tips([NotNull] PreposeGesturesParser.Hands_tipsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.relative_direction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelative_direction([NotNull] PreposeGesturesParser.Relative_directionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.joint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoint([NotNull] PreposeGesturesParser.JointContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.app"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitApp([NotNull] PreposeGesturesParser.AppContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.spine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpine([NotNull] PreposeGesturesParser.SpineContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.restriction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRestriction([NotNull] PreposeGesturesParser.RestrictionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.gesture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGesture([NotNull] PreposeGesturesParser.GestureContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.feet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFeet([NotNull] PreposeGesturesParser.FeetContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.back"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBack([NotNull] PreposeGesturesParser.BackContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.execution_step"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExecution_step([NotNull] PreposeGesturesParser.Execution_stepContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.you"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitYou([NotNull] PreposeGesturesParser.YouContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.rotate_direction_transform"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRotate_direction_transform([NotNull] PreposeGesturesParser.Rotate_direction_transformContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.hips"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHips([NotNull] PreposeGesturesParser.HipsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.shoulders"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShoulders([NotNull] PreposeGesturesParser.ShouldersContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.point_to_transform"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPoint_to_transform([NotNull] PreposeGesturesParser.Point_to_transformContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] PreposeGesturesParser.StatementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.leg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeg([NotNull] PreposeGesturesParser.LegContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.angular_direction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAngular_direction([NotNull] PreposeGesturesParser.Angular_directionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.dont"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDont([NotNull] PreposeGesturesParser.DontContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.ankles"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnkles([NotNull] PreposeGesturesParser.AnklesContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.reference_plane"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReference_plane([NotNull] PreposeGesturesParser.Reference_planeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.sided_joint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSided_joint([NotNull] PreposeGesturesParser.Sided_jointContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.legs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLegs([NotNull] PreposeGesturesParser.LegsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreposeGesturesParser.touch_restriction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTouch_restriction([NotNull] PreposeGesturesParser.Touch_restrictionContext context);
}
} // namespace PreposeGestures
