//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.2.2-SNAPSHOT
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:\work\SurroundWeb\private\AROS\GestureRecognizerKinectV2\\Z3Experiments\Z3Experiments\Parser\PreposeGestures.g4 by ANTLR 4.2.2-SNAPSHOT

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace PreposeGestures {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IPreposeGesturesListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.2.2-SNAPSHOT")]
[System.CLSCompliant(false)]
public partial class PreposeGesturesBaseListener : IPreposeGesturesListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.thumbs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThumbs([NotNull] PreposeGesturesParser.ThumbsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.thumbs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThumbs([NotNull] PreposeGesturesParser.ThumbsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.put_restriction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPut_restriction([NotNull] PreposeGesturesParser.Put_restrictionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.put_restriction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPut_restriction([NotNull] PreposeGesturesParser.Put_restrictionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.align_restriction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAlign_restriction([NotNull] PreposeGesturesParser.Align_restrictionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.align_restriction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAlign_restriction([NotNull] PreposeGesturesParser.Align_restrictionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.direction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirection([NotNull] PreposeGesturesParser.DirectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.direction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirection([NotNull] PreposeGesturesParser.DirectionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.hold_constraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHold_constraint([NotNull] PreposeGesturesParser.Hold_constraintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.hold_constraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHold_constraint([NotNull] PreposeGesturesParser.Hold_constraintContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.wrists"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWrists([NotNull] PreposeGesturesParser.WristsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.wrists"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWrists([NotNull] PreposeGesturesParser.WristsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.repeat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRepeat([NotNull] PreposeGesturesParser.RepeatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.repeat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRepeat([NotNull] PreposeGesturesParser.RepeatContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.execution"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExecution([NotNull] PreposeGesturesParser.ExecutionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.execution"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExecution([NotNull] PreposeGesturesParser.ExecutionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.body_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBody_part([NotNull] PreposeGesturesParser.Body_partContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.body_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBody_part([NotNull] PreposeGesturesParser.Body_partContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.transform"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTransform([NotNull] PreposeGesturesParser.TransformContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.transform"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTransform([NotNull] PreposeGesturesParser.TransformContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.pose"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPose([NotNull] PreposeGesturesParser.PoseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.pose"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPose([NotNull] PreposeGesturesParser.PoseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.center_joint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCenter_joint([NotNull] PreposeGesturesParser.Center_jointContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.center_joint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCenter_joint([NotNull] PreposeGesturesParser.Center_jointContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.side"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSide([NotNull] PreposeGesturesParser.SideContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.side"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSide([NotNull] PreposeGesturesParser.SideContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.rotate_plane_transform"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRotate_plane_transform([NotNull] PreposeGesturesParser.Rotate_plane_transformContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.rotate_plane_transform"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRotate_plane_transform([NotNull] PreposeGesturesParser.Rotate_plane_transformContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.hands"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHands([NotNull] PreposeGesturesParser.HandsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.hands"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHands([NotNull] PreposeGesturesParser.HandsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.motion_constraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMotion_constraint([NotNull] PreposeGesturesParser.Motion_constraintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.motion_constraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMotion_constraint([NotNull] PreposeGesturesParser.Motion_constraintContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.elbows"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElbows([NotNull] PreposeGesturesParser.ElbowsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.elbows"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElbows([NotNull] PreposeGesturesParser.ElbowsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.knees"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKnees([NotNull] PreposeGesturesParser.KneesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.knees"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKnees([NotNull] PreposeGesturesParser.KneesContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.arms"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArms([NotNull] PreposeGesturesParser.ArmsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.arms"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArms([NotNull] PreposeGesturesParser.ArmsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.arm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArm([NotNull] PreposeGesturesParser.ArmContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.arm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArm([NotNull] PreposeGesturesParser.ArmContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.hands_tips"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHands_tips([NotNull] PreposeGesturesParser.Hands_tipsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.hands_tips"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHands_tips([NotNull] PreposeGesturesParser.Hands_tipsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.relative_direction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelative_direction([NotNull] PreposeGesturesParser.Relative_directionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.relative_direction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelative_direction([NotNull] PreposeGesturesParser.Relative_directionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.joint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoint([NotNull] PreposeGesturesParser.JointContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.joint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoint([NotNull] PreposeGesturesParser.JointContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.app"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterApp([NotNull] PreposeGesturesParser.AppContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.app"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitApp([NotNull] PreposeGesturesParser.AppContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.spine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpine([NotNull] PreposeGesturesParser.SpineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.spine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpine([NotNull] PreposeGesturesParser.SpineContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.restriction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRestriction([NotNull] PreposeGesturesParser.RestrictionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.restriction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRestriction([NotNull] PreposeGesturesParser.RestrictionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.gesture"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGesture([NotNull] PreposeGesturesParser.GestureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.gesture"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGesture([NotNull] PreposeGesturesParser.GestureContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.feet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFeet([NotNull] PreposeGesturesParser.FeetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.feet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFeet([NotNull] PreposeGesturesParser.FeetContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.back"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBack([NotNull] PreposeGesturesParser.BackContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.back"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBack([NotNull] PreposeGesturesParser.BackContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.execution_step"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExecution_step([NotNull] PreposeGesturesParser.Execution_stepContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.execution_step"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExecution_step([NotNull] PreposeGesturesParser.Execution_stepContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.you"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterYou([NotNull] PreposeGesturesParser.YouContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.you"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitYou([NotNull] PreposeGesturesParser.YouContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.rotate_direction_transform"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRotate_direction_transform([NotNull] PreposeGesturesParser.Rotate_direction_transformContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.rotate_direction_transform"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRotate_direction_transform([NotNull] PreposeGesturesParser.Rotate_direction_transformContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.hips"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHips([NotNull] PreposeGesturesParser.HipsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.hips"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHips([NotNull] PreposeGesturesParser.HipsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.shoulders"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShoulders([NotNull] PreposeGesturesParser.ShouldersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.shoulders"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShoulders([NotNull] PreposeGesturesParser.ShouldersContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.point_to_transform"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPoint_to_transform([NotNull] PreposeGesturesParser.Point_to_transformContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.point_to_transform"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPoint_to_transform([NotNull] PreposeGesturesParser.Point_to_transformContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] PreposeGesturesParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] PreposeGesturesParser.StatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.leg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeg([NotNull] PreposeGesturesParser.LegContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.leg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeg([NotNull] PreposeGesturesParser.LegContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.angular_direction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAngular_direction([NotNull] PreposeGesturesParser.Angular_directionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.angular_direction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAngular_direction([NotNull] PreposeGesturesParser.Angular_directionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.dont"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDont([NotNull] PreposeGesturesParser.DontContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.dont"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDont([NotNull] PreposeGesturesParser.DontContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.ankles"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnkles([NotNull] PreposeGesturesParser.AnklesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.ankles"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnkles([NotNull] PreposeGesturesParser.AnklesContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.reference_plane"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReference_plane([NotNull] PreposeGesturesParser.Reference_planeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.reference_plane"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReference_plane([NotNull] PreposeGesturesParser.Reference_planeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.sided_joint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSided_joint([NotNull] PreposeGesturesParser.Sided_jointContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.sided_joint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSided_joint([NotNull] PreposeGesturesParser.Sided_jointContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.legs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLegs([NotNull] PreposeGesturesParser.LegsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.legs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLegs([NotNull] PreposeGesturesParser.LegsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreposeGesturesParser.touch_restriction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTouch_restriction([NotNull] PreposeGesturesParser.Touch_restrictionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreposeGesturesParser.touch_restriction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTouch_restriction([NotNull] PreposeGesturesParser.Touch_restrictionContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace PreposeGestures
